### ISSUE TITLE
add a parameter ( if possible ) to turn certificate verification off

### ISSUE THREAD

**Issue by davidfrazao** [selivan/kibana-backup-simple#13]
HI Selivan 

Nice tool and it help a lot.

Could you add a parameter ( if possible ) to turn certificate verification **off** or suggest a workaround. 

error mgs :
 
requests.exceptions.SSLError: HTTPSConnectionPool(host='kibana.XXXXXX.zzzzzzz.vvvv', port=5601): Max retries exceeded with url: /api/saved_objects/_export (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)'),))

thx in advance

**Comment by selivan** [comment]
Hi @davidfrazao 

Please check out if code from this branch works for you: https://github.com/selivan/kibana-backup-simple/tree/issue-13 New option us `--no-ssl-verify`.

**Comment by davidfrazao** [comment]
hi Selivan 

i have tested the python script from isssue-13 branch and it is working. 

Return line  :
 
 InsecureRequestWarning,
/root/.local/lib/python3.5/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'XXXXXX.zzzzzzzz.wwww.ttt' . Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

Thx again

**Comment by selivan** [comment]
Merged in https://github.com/selivan/kibana-backup-simple/pull/14

Updated VERSION to trigger new pypi build
