### ISSUE TITLE
backup files location

### ISSUE THREAD

**Issue by donnatxq** [selivan/kibana-backup-simple#16]
Hi selivan,
If I want to save the backup files under a defined location and restore the datum from the location, how could I do? Thanks.

**Comment by selivan** [comment]
You can use this option:

`--backup-file=/some/path/backup.ndjson`

As alternative to this option you can just redirect stdout (for backup) or stdin(for restore).

For backup and resore all kibana namespaces there is an option

`--backup-file-prefix=/some/path/backup-` , files should have .ndjson extension.

Also works for backup and restore.

**Comment by donnatxq** [comment]
Thank you, it works. :)
________________________________
发件人: Pavel Selivanov ***@***.***>
发送时间: 2022年7月20日 11:46
收件人: selivan/kibana-backup-simple ***@***.***>
抄送: donnatxq ***@***.***>; Author ***@***.***>
主题: Re: [selivan/kibana-backup-simple] backup files location (Issue #16)


Closed #16<https://github.com/selivan/kibana-backup-simple/issues/16> as completed.

―
