### ISSUE TITLE
Kibana export

### ISSUE THREAD

**Issue by ehmueller** [selivan/kibana-backup-simple#3]
Hello,

Have you thought about adding Kibana backup to your script so you can backup your index-patterns and your field formats?
https://www.elastic.co/guide/en/kibana/current/saved-objects-api-export.html

thanks
Eric

**Comment by selivan** [comment]
@ehmueller Current version of  the script is using `/api/saved_objects/_import` and `/api/saved_objects/_export`, it saves index patterns.

I probably should add `space_id`, now it always uses the default space.

**Comment by ehmueller** [comment]
OK great, I do have multiple spaces that need to be backed up so that would be great if you can backup all spaces.  thanks!

**Comment by selivan** [comment]
@ehmueller I added support for different spaces in a branch feature-space-id: https://github.com/selivan/kibana-backup-simple/tree/feature-space-id

But with my Kibana 7.2.1 it doesn't work:

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:5601/s/default/api/saved_objects/_export
```

I am using [Export objects API](https://www.elastic.co/guide/en/kibana/master/saved-objects-api-export.html#saved-objects-api-export-request) as descriped in docs, and spaces API shows that space with id=default exist:

```
curl -s http://127.0.0.1:5601/api/spaces/space | jq
[
  {
    "id": "default",
    "name": "Default",
    "description": "This is your default space!",
    "color": "#00bfb3",
    "disabledFeatures": [],
    "_reserved": true
  }
]
```

Could you please check if it works for you?

**Comment by selivan** [comment]
@ehmueller That's OK, I add another space to Kibana and it works fine with it. Seems that it does not work only with `default` space.
