### ISSUE TITLE
Restore specific objects

### ISSUE THREAD

**Issue by elisboa** [selivan/kibana-backup-simple#4]
Hi, is it possible to restore an specific object, such as a dashboard or a view or a specific index from the snapshot? If so, how can I do that?

**Comment by selivan** [comment]
Hi,

This script can not backup separate objects.

If you exported this object from Kibana web interface(Management - Saved Objects - select object - Export) to a file, you can restore it with this script the usual way:

`cat object.ndjson | kibana-backup.py [--kibana-url KIBANA_URL] [--user USER] [--password PASSWORD] restore`

**Comment by elisboa** [comment]
Thank you for your attention :-)
